### ISSUE TITLE
answer of "您有什么诉求" has some character &lt;p&gt; like followings

### ISSUE THREAD

**Issue by shanchenqi1** [grimoirelab-gitee/grimoirelab-elk-surveyqq#4]
"options" : [
                      {
                        "id" : "o-101-a019",
                        "checked" : 1,
                        "text" : """&lt;p&gt;CI平台&lt;/p&gt;
""",
                        "sort_no" : 0
                      },
                      {
                        "id" : "o-102-bd60",
                        "checked" : 1,
                        "text" : """&lt;p&gt;软件包下载&lt;/p&gt;
""",
                        "sort_no" : 0
                      }

**Comment by shanchenqi** [comment]
This is a problem with surveyqq itself. When I create a new questionnaire, this question will not appear
